plugins { id 'com.android.application' }

android {
    namespace 'nl.laptopjacht'
    compileSdk 34

    defaultConfig {
        applicationId "nl.laptopjacht"
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            // debug-signed so it can be sideloaded without a keystore
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
